
# Fichier : lang.py
# Contient les traductions en français, anglais, malgache pour l'application DEVIABTP

translations = {
    "fr": {
        "title": "DEVIABTP - Générateur de devis bâtiment",
        "upload_prompt": "Téléversez le plan ou croquis de votre infrastructure :",
        "project_name": "Nom du projet",
        "generate_pdf": "Générer le devis PDF",
        "download_pdf": "Télécharger le PDF",
        "language_choice": "Choisissez la langue",
        "success": "✅ PDF généré avec succès ! Cliquez ci-dessous pour télécharger.",
        "missing_fields": "❌ Veuillez remplir tous les champs.",
        "loading": "Génération en cours...",
        "estimation": "Estimation automatique basée sur le croquis",
        "materials_table": "Tableau des matériaux estimés",
        "visualization": "Visualisation graphique",
        "add_material": "Ajouter un matériau",
        "material": "Matériau",
        "quantity": "Quantité",
        "unit_price": "Prix unitaire",
        "total_price": "Prix total",
        "client_name": "Nom du client",
        "export_excel": "Exporter en Excel",
        "notes": "Notes complémentaires",
        "invoice": "Facture finale"
    },
    "en": {
        "title": "DEVIABTP - Building Estimate Generator",
        "upload_prompt": "Upload the plan or sketch of your infrastructure:",
        "project_name": "Project Name",
        "generate_pdf": "Generate PDF Estimate",
        "download_pdf": "Download PDF",
        "language_choice": "Choose language",
        "success": "✅ PDF successfully generated! Click below to download.",
        "missing_fields": "❌ Please fill in all fields.",
        "loading": "Generating...",
        "estimation": "Automatic estimation based on the sketch",
        "materials_table": "Estimated Materials Table",
        "visualization": "Graphical Visualization",
        "add_material": "Add Material",
        "material": "Material",
        "quantity": "Quantity",
        "unit_price": "Unit Price",
        "total_price": "Total Price",
        "client_name": "Client Name",
        "export_excel": "Export to Excel",
        "notes": "Additional Notes",
        "invoice": "Final Invoice"
    },
    "mg": {
        "title": "DEVIABTP - Teti-bola amin'ny fanorenana",
        "upload_prompt": "Alefaso ny drafitra na kisary fanorenana :",
        "project_name": "Anaran'ny tetikasa",
        "generate_pdf": "Mamokatra teti-bola PDF",
        "download_pdf": "Alaivo ny PDF",
        "language_choice": "Misafidiana fiteny",
        "success": "✅ Vita ny PDF ! Tsindrio eto ambany raha haka azy.",
        "missing_fields": "❌ Fenoy ny saha rehetra azafady.",
        "loading": "Eo am-panamboarana...",
        "estimation": "Fanombanana mandeha ho azy avy amin’ny kisary",
        "materials_table": "Tabilao fitaovana tombanana",
        "visualization": "Fampisehoana amin’ny sary",
        "add_material": "Manampy fitaovana",
        "material": "Fitaovana",
        "quantity": "Isan'ny",
        "unit_price": "Vidiny isaky ny iray",
        "total_price": "Vidiny manontolo",
        "client_name": "Anaran'ny mpanjifa",
        "export_excel": "Hondrana amin’ny Excel",
        "notes": "Fanamarihana fanampiny",
        "invoice": "Faktiora farany"
    }
}
